#!/usr/bin/env tsx
import { writeFileSync } from "fs";
import { resolve } from "path";
import { ASSETS_CDN_BASE, ASSETS_EXT } from "./assets-cdn.config.ts";

const INDEX_URL =
  "https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/index_min/en/characters.json";

const OUT_PATH = resolve(process.cwd(), "src/data/characters.ts");

const PATH_MAP: Record<string, string> = {
  Knight: "Preservation",
  Rogue: "The Hunt",
  Mage: "Erudition",
  Shaman: "Harmony",
  Warlock: "Nihility",
  Warrior: "Destruction",
  Priest: "Abundance",
  Memory: "Remembrance",
  Elation: "Elation",
};

const ELEMENT_MAP: Record<string, string> = {
  Thunder: "Lightning",
};

// mirror of src/types/character.ts
interface RawCharacter {
  id: string;
  name: string;
  tag: string;
  rarity: number;
  path: string;
  element: string;
  icon: string;
  preview: string;
  portrait: string;
}

function mapPath(raw: string): string {
  const mapped = PATH_MAP[raw];
  if (!mapped) {
    console.warn(`  ⚠  Unknown path "${raw}" — writing as-is. Add it to PATH_MAP.`);
    return raw;
  }
  return mapped;
}

function mapElement(raw: string): string {
  return ELEMENT_MAP[raw] ?? raw;
}

async function main() {
  console.log("Fetching character index from Mar-7th/StarRailRes...");
  const res = await fetch(INDEX_URL);
  if (!res.ok) throw new Error(`Failed to fetch: ${res.status} ${res.statusText}`);

  const raw: Record<string, RawCharacter> = await res.json();
  const entries = Object.values(raw);

  console.log(`  Found ${entries.length} characters.`);

  entries.sort((a, b) => Number(a.id) - Number(b.id));

  const lines: string[] = [
    `// AUTO-GENERATED by scripts/generate-characters.ts — do not edit by hand.`,
    `// Re-run \`npm run generate:characters\` after a new patch to update.`,
    `//`,
    `// Metadata source: https://github.com/Mar-7th/StarRailRes`,
    `// Images: ${ASSETS_CDN_BASE} (see src/config/assets.ts)`,
    ``,
    `import type { Character } from "../types/character";`,
    `import { ASSETS_CDN } from "../config/assets";`,
    ``,
    `const ASSETS = ASSETS_CDN;`,
    ``,
    `export const CHARACTERS: Character[] = [`,
  ];

  for (const c of entries) {
    const path = mapPath(c.path);
    const element = mapElement(c.element);

    lines.push(`  {`);
    lines.push(`    id: ${c.id},`);
    if (Number.parseInt(c.id) >= 8000) {
      lines.push(`    name: "Trailblazer",`);
    } else {
      lines.push(`    name: ${JSON.stringify(c.name)},`);
    }
    lines.push(`    element: "${element}",`);
    lines.push(`    path: "${path}",`);
    lines.push(`    rarity: ${c.rarity},`);
    lines.push(`    icon: \`\${ASSETS}/characters/icon/${c.id}.${ASSETS_EXT}\`,`);
    lines.push(`    preview: \`\${ASSETS}/characters/preview/${c.id}.${ASSETS_EXT}\`,`);
    lines.push(`    portrait: \`\${ASSETS}/characters/portrait/${c.id}.${ASSETS_EXT}\`,`);
    lines.push(`  },`);
  }

  lines.push(`];`);
  lines.push(``);
  lines.push(`export function getCharacterById(id: number): Character | undefined {`);
  lines.push(`  return CHARACTERS.find((c) => c.id === id);`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`export function getCharactersByElement(element: Character["element"]): Character[] {`);
  lines.push(`  return CHARACTERS.filter((c) => c.element === element);`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`export function getCharactersByPath(path: Character["path"]): Character[] {`);
  lines.push(`  return CHARACTERS.filter((c) => c.path === path);`);
  lines.push(`}`);
  lines.push(``);

  writeFileSync(OUT_PATH, lines.join("\n"), "utf-8");
  console.log(`  ✓ Written to ${OUT_PATH}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});