import fs from "fs";

const semver = fs.existsSync("VERSION")
  ? fs.readFileSync("VERSION", "utf8").trim()
  : "v0.0.0";

const version = semver;
const buildDate = new Date().toISOString().slice(0, 10);

const out = [
  "// AUTO-GENERATED by scripts/write-version.ts — do not edit by hand.",
  "",
  `export const VERSION = "${version}";`,
  `export const BUILD_DATE = "${buildDate}";`,
  "export default VERSION;",
  "",
].join("\n");

fs.mkdirSync("src/data", { recursive: true });
fs.writeFileSync("src/data/version.ts", out);
console.log("WROTE src/data/version.ts ->", version);