import fs from "fs";
import { execSync } from "child_process";

function tryExec(cmd: string): string | null {
  try {
    return execSync(cmd, {
      stdio: ["ignore", "pipe", "ignore"],
    }).toString().trim();
  } catch {
    return null;
  }
}

const sha =
  tryExec("git rev-parse --short HEAD") ??
  process.env.VERCEL_GIT_COMMIT_SHA?.slice(0, 7) ??
  "dev";

const date = new Date().toISOString().slice(0, 10).replace(/-/g, "");

const version = `alpha-${date}-${sha}`;

const out = [
  "// AUTO-GENERATED by scripts/write-version.ts — do not edit by hand.",
  "",
  `export const VERSION = "${version}";`,
  "export default VERSION;",
  "",
].join("\n");

fs.mkdirSync("src/data", { recursive: true });
fs.writeFileSync("src/data/version.ts", out);
console.log("WROTE src/data/version.ts ->", version);